version: '3.8'
services:
  gateway:
    build: ./gateway
    image: docker_gateway
    container_name: gateway_cont
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
#      - TZ=Europe/Moscow
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    image: docker_server
    container_name: server_cont
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
#      - TZ=Europe/Moscow
      - DB_NAME=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:13.7-alpine
    container_name: shareit_postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot